/**
 * AIValidator Implementation
 *
 * Conflict detection with clear separation between:
 * - AI-generated CPA mathematics
 * - Human-written safety validation
 */

#include "ai_validator.hpp"
#include <sstream>
#include <iomanip>

namespace skyguard {

// ============================================
// Main Entry Point
// ============================================

std::optional<ConflictAlert> AIValidator::check_conflict(
    const FlightState& flight1,
    const FlightState& flight2
) {
    // ----------------------------------------
    // SAFETY GATE: Input Validation (Human-written)
    // ----------------------------------------
    if (!validate_inputs(flight1, flight2)) {
        // Invalid inputs - cannot safely calculate
        // In production, would log this anomaly
        return std::nullopt;
    }

    // ----------------------------------------
    // AI LOGIC: Calculate CPA
    // ----------------------------------------
    double time_to_cpa = 0.0;
    double distance_at_cpa = 0.0;

    bool cpa_valid = calculate_cpa(
        flight1.position, flight1.velocity,
        flight2.position, flight2.velocity,
        time_to_cpa, distance_at_cpa
    );

    if (!cpa_valid) {
        // CPA calculation failed (e.g., diverging aircraft)
        return std::nullopt;
    }

    // ----------------------------------------
    // SAFETY GATE: Output Validation (Human-written)
    // ----------------------------------------
    if (!validate_output(time_to_cpa, distance_at_cpa)) {
        // Output values unreasonable - don't trust them
        return std::nullopt;
    }

    // ----------------------------------------
    // Evaluate Separation Standards
    // ----------------------------------------

    // Convert to nautical miles for horizontal
    double horizontal_nm = distance_at_cpa / constants::NM_TO_METERS;

    // Vertical separation at CPA (approximate - assume constant altitude)
    double vertical_ft = std::abs(flight1.altitude - flight2.altitude);

    // Check against separation standards
    bool horizontal_violation =
        horizontal_nm < constants::MIN_HORIZONTAL_SEPARATION;
    bool vertical_violation =
        vertical_ft < constants::MIN_VERTICAL_SEPARATION;

    // Only alert if BOTH separations are violated
    // (Aircraft can be close horizontally if well-separated vertically)
    if (!horizontal_violation || !vertical_violation) {
        return std::nullopt;
    }

    // Only care about conflicts within lookahead window
    if (time_to_cpa > constants::CONFLICT_LOOKAHEAD) {
        return std::nullopt;
    }

    // ----------------------------------------
    // Build Alert
    // ----------------------------------------
    ConflictAlert alert;
    alert.flight1 = flight1.id;
    alert.flight2 = flight2.id;
    alert.time_to_cpa = time_to_cpa;
    alert.min_separation = horizontal_nm;
    alert.altitude_difference = static_cast<Feet>(vertical_ft);
    alert.detected_at = Clock::now();
    alert.severity = determine_severity(time_to_cpa, horizontal_nm, vertical_ft);
    alert.recommendation = generate_recommendation(
        flight1, flight2,
        flight1.altitude - flight2.altitude
    );

    return alert;
}

// ============================================
// LAYER 1: AI-GENERATED CPA CALCULATION
// ============================================

/**
 * AI-GENERATED: Closest Point of Approach calculation.
 *
 * This algorithm was generated by Claude based on standard
 * aviation CPA formulas. The math is:
 *
 *   t_cpa = -(Pr · Vr) / |Vr|²
 *   d_cpa = |Pr + Vr * t_cpa|
 *
 * Where:
 *   Pr = relative position (pos1 - pos2)
 *   Vr = relative velocity (vel1 - vel2)
 */
bool AIValidator::calculate_cpa(
    const Vec3& pos1, const Vec3& vel1,
    const Vec3& pos2, const Vec3& vel2,
    double& time_to_cpa,
    double& distance_at_cpa
) {
    // Calculate relative position and velocity
    Vec3 rel_pos = pos1 - pos2;
    Vec3 rel_vel = vel1 - vel2;

    // Check for divide-by-zero (human-written safety check)
    double rel_vel_sq = rel_vel.magnitude_squared();
    if (!check_divide_by_zero(rel_vel_sq)) {
        // Aircraft have essentially same velocity
        // Use current distance as CPA
        distance_at_cpa = std::sqrt(rel_pos.magnitude_squared());
        time_to_cpa = 0.0;
        return true;
    }

    // Time to CPA: t = -(Pr · Vr) / |Vr|²
    double dot_product = rel_pos.dot(rel_vel);
    time_to_cpa = -dot_product / rel_vel_sq;

    // If time is negative, aircraft are diverging (CPA was in past)
    if (time_to_cpa < 0.0) {
        // Use current distance
        distance_at_cpa = std::sqrt(rel_pos.magnitude_squared());
        time_to_cpa = 0.0;
        return true;
    }

    // Position at CPA: P_cpa = Pr + Vr * t_cpa
    Vec3 pos_at_cpa = rel_pos + rel_vel * time_to_cpa;
    distance_at_cpa = std::sqrt(pos_at_cpa.magnitude_squared());

    return true;
}

// ============================================
// LAYER 2: HUMAN-WRITTEN SAFETY GATE
// ============================================

/**
 * HUMAN-WRITTEN: Input validation.
 *
 * I wrote this function to catch edge cases that the AI-generated
 * CPA math doesn't handle:
 *
 * 1. NaN/Inf from sensor errors or transmission corruption
 * 2. Unrealistic speeds that would indicate bad data
 * 3. Stale data that shouldn't be used for conflict detection
 */
bool AIValidator::validate_inputs(
    const FlightState& flight1,
    const FlightState& flight2
) {
    // Check position values for NaN/Inf
    if (!std::isfinite(flight1.position.x) ||
        !std::isfinite(flight1.position.y) ||
        !std::isfinite(flight1.position.z) ||
        !std::isfinite(flight2.position.x) ||
        !std::isfinite(flight2.position.y) ||
        !std::isfinite(flight2.position.z)) {
        return false;
    }

    // Check velocity values for NaN/Inf
    if (!std::isfinite(flight1.velocity.x) ||
        !std::isfinite(flight1.velocity.y) ||
        !std::isfinite(flight1.velocity.z) ||
        !std::isfinite(flight2.velocity.x) ||
        !std::isfinite(flight2.velocity.y) ||
        !std::isfinite(flight2.velocity.z)) {
        return false;
    }

    // Check for unrealistic speeds (> Mach 3)
    double speed1_sq = flight1.velocity.magnitude_squared();
    double speed2_sq = flight2.velocity.magnitude_squared();

    if (speed1_sq > MAX_AIRCRAFT_SPEED * MAX_AIRCRAFT_SPEED ||
        speed2_sq > MAX_AIRCRAFT_SPEED * MAX_AIRCRAFT_SPEED) {
        return false;
    }

    // Check altitude values
    if (!std::isfinite(flight1.altitude) ||
        !std::isfinite(flight2.altitude)) {
        return false;
    }

    // Don't use stale data for conflict detection
    if (flight1.is_stale(10.0) || flight2.is_stale(10.0)) {
        return false;
    }

    return true;
}

/**
 * HUMAN-WRITTEN: Divide-by-zero prevention.
 *
 * The CPA formula divides by |Vr|². If both aircraft have
 * the same velocity (e.g., both heading north at 450 knots),
 * then Vr = 0 and we'd have division by zero.
 *
 * In this case, we use the current separation as the CPA
 * since the relative geometry isn't changing.
 */
bool AIValidator::check_divide_by_zero(double rel_velocity_sq) {
    return rel_velocity_sq >= MIN_RELATIVE_VELOCITY_SQ;
}

/**
 * HUMAN-WRITTEN: Output validation.
 *
 * Ensures the CPA calculation produced reasonable results:
 * - Time should be non-negative and within lookahead
 * - Distance should be non-negative and finite
 */
bool AIValidator::validate_output(double time_to_cpa, double distance) {
    // Time should be non-negative
    if (time_to_cpa < 0.0) {
        return false;
    }

    // Time shouldn't be too far in future (numerical issues)
    if (time_to_cpa > constants::CONFLICT_LOOKAHEAD * 2) {
        return false;
    }

    // Distance should be finite and non-negative
    if (!std::isfinite(distance) || distance < 0.0) {
        return false;
    }

    return true;
}

/**
 * HUMAN-WRITTEN: Severity determination.
 *
 * Based on FAA/ICAO standards:
 * - CRITICAL: CPA < 30s with insufficient separation
 * - WARNING: CPA 30-60s with potential violation
 */
AlertSeverity AIValidator::determine_severity(
    double time_to_cpa,
    double horizontal_nm,
    double vertical_ft
) {
    // Severity based on time to CPA
    if (time_to_cpa < 30.0) {
        return AlertSeverity::CRITICAL;
    }

    // Also critical if separation is very small
    if (horizontal_nm < 3.0 && vertical_ft < 500.0) {
        return AlertSeverity::CRITICAL;
    }

    return AlertSeverity::WARNING;
}

/**
 * HUMAN-WRITTEN: Recommendation generation.
 *
 * Simple logic: lower aircraft should descend, higher should climb.
 * In real ATC, this would be much more sophisticated.
 */
std::string AIValidator::generate_recommendation(
    const FlightState& flight1,
    const FlightState& flight2,
    double vertical_diff
) {
    std::ostringstream oss;

    if (vertical_diff > 0) {
        // flight1 is higher - tell flight2 to descend
        int new_alt = static_cast<int>(flight2.altitude / 1000) - 1;
        oss << "FL" << flight2.id << " descend to FL" << (new_alt * 10);
    } else {
        // flight2 is higher - tell flight1 to descend
        int new_alt = static_cast<int>(flight1.altitude / 1000) - 1;
        oss << "FL" << flight1.id << " descend to FL" << (new_alt * 10);
    }

    return oss.str();
}

// ============================================
// Vec3 Implementation (from types.hpp)
// ============================================

double Vec3::magnitude() const {
    return std::sqrt(magnitude_squared());
}

} // namespace skyguard
