#pragma once

/**
 * AIValidator - Conflict Detection with Safety Gate
 *
 * TWO-LAYER DESIGN:
 *
 * Layer 1: AI-Generated Conflict Logic
 *   - Closest Point of Approach (CPA) calculation
 *   - Geometry/calculus for 3D trajectory intersection
 *   - Generated by Claude, documented in comments
 *
 * Layer 2: Human-Written Safety Gate
 *   - Input validation (NaN, Inf, out-of-range)
 *   - Divide-by-zero prevention
 *   - Output clamping to physical limits
 *   - 100% human-written, explicitly documented
 *
 * For interview: "I used AI to generate the CPA geometry—it's
 * well-documented math that I validated against aviation references.
 * But I wrote the safety gate myself to handle edge cases the AI
 * might not consider: divide-by-zero when aircraft have matching
 * velocities, NaN propagation from sensor errors, and unrealistic
 * speed values."
 */

#include "types.hpp"
#include "flight_packet.hpp"
#include <optional>
#include <cmath>
#include <string>

namespace skyguard {

/**
 * AIValidator class
 */
class AIValidator {
public:
    AIValidator() = default;

    /**
     * Check if two flights are in conflict.
     *
     * @param flight1 First flight state
     * @param flight2 Second flight state
     * @return ConflictAlert if conflict detected, nullopt otherwise
     */
    std::optional<ConflictAlert> check_conflict(
        const FlightState& flight1,
        const FlightState& flight2
    );

private:
    // ========================================
    // LAYER 1: AI-GENERATED CONFLICT LOGIC
    // ========================================
    // The following CPA calculation was generated by Claude.
    // Reference: FAA Order 7110.65, ICAO Doc 4444
    // The math calculates when two aircraft will be closest
    // to each other given their current positions and velocities.

    /**
     * Calculate Closest Point of Approach (CPA).
     *
     * AI-GENERATED ALGORITHM:
     *
     * Given:
     *   Aircraft A at position Pa with velocity Va
     *   Aircraft B at position Pb with velocity Vb
     *
     * The relative position at time t is:
     *   P(t) = (Pa - Pb) + (Va - Vb) * t
     *        = Pr + Vr * t
     *
     * Where:
     *   Pr = Pa - Pb (relative position)
     *   Vr = Va - Vb (relative velocity)
     *
     * Distance squared at time t:
     *   D²(t) = |P(t)|² = |Pr + Vr * t|²
     *         = Pr·Pr + 2*Pr·Vr*t + Vr·Vr*t²
     *
     * To find minimum, take derivative and set to zero:
     *   d(D²)/dt = 2*Pr·Vr + 2*Vr·Vr*t = 0
     *
     * Solving for t:
     *   t_cpa = -(Pr · Vr) / (Vr · Vr)
     *
     * Then:
     *   d_cpa = |Pr + Vr * t_cpa|
     *
     * @param pos1 Position of aircraft 1 (meters)
     * @param vel1 Velocity of aircraft 1 (m/s)
     * @param pos2 Position of aircraft 2 (meters)
     * @param vel2 Velocity of aircraft 2 (m/s)
     * @param[out] time_to_cpa Time until CPA (seconds)
     * @param[out] distance_at_cpa Minimum distance (meters)
     * @return true if calculation successful, false if inputs invalid
     */
    bool calculate_cpa(
        const Vec3& pos1, const Vec3& vel1,
        const Vec3& pos2, const Vec3& vel2,
        double& time_to_cpa,
        double& distance_at_cpa
    );

    // ========================================
    // LAYER 2: HUMAN-WRITTEN SAFETY GATE
    // ========================================
    // Everything below this line is 100% human-written.
    // These functions validate inputs and outputs to catch
    // edge cases that AI-generated math might not handle.

    /**
     * HUMAN-WRITTEN: Validate input flight states.
     *
     * Checks for:
     * - NaN/Inf values (sensor errors, transmission corruption)
     * - Unrealistic speeds (> Mach 3)
     * - Zero velocity vectors (would cause divide-by-zero in CPA)
     *
     * @param flight1 First flight state
     * @param flight2 Second flight state
     * @return true if inputs are safe for CPA calculation
     */
    bool validate_inputs(const FlightState& flight1, const FlightState& flight2);

    /**
     * HUMAN-WRITTEN: Check for divide-by-zero conditions.
     *
     * The CPA formula has division by |Vr|². If both aircraft
     * have identical velocities, Vr = 0 and we'd divide by zero.
     *
     * @param rel_velocity_sq Squared magnitude of relative velocity
     * @return true if safe to proceed, false if would cause div-by-zero
     */
    bool check_divide_by_zero(double rel_velocity_sq);

    /**
     * HUMAN-WRITTEN: Validate and clamp CPA output values.
     *
     * Ensures results are within physical limits:
     * - Time to CPA: 0 to lookahead limit
     * - Distance: non-negative
     *
     * @param time_to_cpa Time value to validate
     * @param distance Distance value to validate
     * @return true if values are reasonable
     */
    bool validate_output(double time_to_cpa, double distance);

    /**
     * HUMAN-WRITTEN: Determine severity based on separation.
     *
     * @param time_to_cpa Seconds until CPA
     * @param horizontal_nm Horizontal separation in nautical miles
     * @param vertical_ft Vertical separation in feet
     * @return Alert severity level
     */
    AlertSeverity determine_severity(
        double time_to_cpa,
        double horizontal_nm,
        double vertical_ft
    );

    /**
     * HUMAN-WRITTEN: Generate recommendation text.
     *
     * @param flight1 First flight
     * @param flight2 Second flight
     * @param vertical_diff Altitude difference (positive if 1 is higher)
     * @return Recommended action string
     */
    std::string generate_recommendation(
        const FlightState& flight1,
        const FlightState& flight2,
        double vertical_diff
    );

    // ========================================
    // Constants
    // ========================================

    // Minimum relative velocity squared (m²/s²) to avoid divide-by-zero
    // Equivalent to ~0.2 knots relative speed
    static constexpr double MIN_RELATIVE_VELOCITY_SQ = 0.01;

    // Maximum realistic aircraft speed (m/s) - about Mach 3
    static constexpr double MAX_AIRCRAFT_SPEED = 1000.0;
};

} // namespace skyguard
